export const leadPageCopy = {
  es: {
    navService:'Diseño web', navBudget:'Presupuesto',
    service:{ eyebrow:'DISEÑO Y DESARROLLO WEB', title:'Una web corporativa que trabaja tan bien como tu negocio.', intro:'Diseño webs rápidas, claras y preparadas para convertir visitas en oportunidades. Sin plantillas genéricas ni procesos opacos.', cta:'Calcula tu proyecto', secondary:'Ver precios', proof:'10 años diseñando y construyendo productos digitales', section:'De la estrategia a una web lista para crecer.', cards:[['01','Dirección clara','Arquitectura, mensajes y recorridos pensados alrededor de tus objetivos.'],['02','Diseño a medida','Una identidad digital propia, responsive y accesible.'],['03','Desarrollo sólido','Código mantenible, rendimiento y una base técnica preparada para SEO.']], processTitle:'Un proceso directo, sin caja negra.', process:['Definimos objetivos, públicos y alcance.','Diseño la estructura y el sistema visual.','Desarrollo, pruebo y publico la web.'], final:'Tu próxima web puede empezar hoy.', finalText:'Obtén una primera horquilla sin reuniones ni formularios interminables.'},
    pricing:{ eyebrow:'PRECIOS SIN RODEOS', title:'¿Cuánto cuesta una web corporativa?', intro:'Una web sencilla parte de 700 € antes de IVA. El importe final depende del tamaño, los contenidos y las funcionalidades.', cta:'Calcular mi web', base:'Desde', included:'La base incluye', includedItems:['Una página responsive','Un idioma','Diseño y desarrollo','Formulario de contacto','Textos aportados por el cliente'], factors:'Qué modifica el precio', factorItems:[['Más páginas','Una arquitectura mayor requiere más diseño, contenido y pruebas.'],['Idiomas y contenidos','Traducción, redacción o identidad visual se presupuestan aparte.'],['Funciones','CMS, blog, reservas e integraciones amplían el alcance.']], note:'La calculadora ofrece una horquilla orientativa. Revisaré el alcance antes de emitir un presupuesto definitivo.'}
  },
  ca: {
    navService:'Disseny web', navBudget:'Pressupost',
    service:{ eyebrow:'DISSENY I DESENVOLUPAMENT WEB', title:'Una web corporativa que treballa tan bé com el teu negoci.', intro:'Dissenyo webs ràpides, clares i preparades per convertir visites en oportunitats. Sense plantilles genèriques ni processos opacs.', cta:'Calcula el teu projecte', secondary:'Veure preus', proof:'10 anys dissenyant i construint productes digitals', section:'De l’estratègia a una web preparada per créixer.', cards:[['01','Direcció clara','Arquitectura, missatges i recorreguts pensats al voltant dels teus objectius.'],['02','Disseny a mida','Una identitat digital pròpia, responsive i accessible.'],['03','Desenvolupament sòlid','Codi mantenible, rendiment i una base tècnica preparada per a SEO.']], processTitle:'Un procés directe, sense caixa negra.', process:['Definim objectius, públics i abast.','Dissenyo l’estructura i el sistema visual.','Desenvolupo, provo i publico la web.'], final:'La teva pròxima web pot començar avui.', finalText:'Obté una primera forquilla sense reunions ni formularis interminables.'},
    pricing:{ eyebrow:'PREUS SENSE VOLTES', title:'Quant costa una web corporativa?', intro:'Una web senzilla parteix de 700 € abans d’IVA. L’import final depèn de la mida, els continguts i les funcionalitats.', cta:'Calcular la meva web', base:'Des de', included:'La base inclou', includedItems:['Una pàgina responsive','Un idioma','Disseny i desenvolupament','Formulari de contacte','Textos aportats pel client'], factors:'Què modifica el preu', factorItems:[['Més pàgines','Una arquitectura més gran requereix més disseny, contingut i proves.'],['Idiomes i continguts','Traducció, redacció o identitat visual es pressuposten a part.'],['Funcions','CMS, blog, reserves i integracions amplien l’abast.']], note:'La calculadora ofereix una forquilla orientativa. Revisaré l’abast abans d’emetre un pressupost definitiu.'}
  }
}
